volumes:
  pg_data:
  static:
  media:

services:
  db:
    image: postgres:13
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL","pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5 
  backend:
    depends_on:
      db:
        condition: service_healthy 

    image: rodypa/foodgram_backend
    env_file: .env
    volumes:
      - static:/backend_static
      - media:/app/foodgram/media/
  frontend:
    env_file: .env
    image: rodypa/foodgram_frontend
    command: cp -r /app/build/. /static/
    volumes:
      - static:/static/
  gateway:
    depends_on:
      - backend
    image: rodypa/foodgram_gateway
    volumes:
      - static:/staticfiles/
      - media:/app/foodgram/media/
    ports:
      - 8050:80