# Generated by Django 5.0.6 on 2024-06-10 02:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True, verbose_name='Название тега')),
                ('slug', models.SlugField(unique=True, verbose_name='уникальное название тега')),
            ],
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='Название рецепта')),
                ('image', models.ImageField(blank=True, upload_to='recipes_images/', verbose_name='Картинка рецепта')),
                ('text', models.TextField(max_length=512, verbose_name='Текстовое описание')),
                ('cooking_time', models.TimeField(verbose_name='Время приготовления')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Автор рецепта')),
                ('tags', models.ManyToManyField(blank=True, to='recipes.tag', verbose_name='Соответствующие теги')),
            ],
        ),
    ]
