# Generated by Django 5.0.6 on 2024-06-13 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0006_alter_favoriterecipe_user_shopingcart_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='short_link',
            field=models.CharField(default='9vmTxR8oYQZkdvcgr22V6c', max_length=128, unique=True),
        ),
    ]
