# Generated by Django 5.0.6 on 2024-06-13 14:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0008_alter_recipe_short_link'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='recipe',
            name='author_name_unique',
        ),
        migrations.AlterField(
            model_name='recipe',
            name='cooking_time',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator], verbose_name='Время приготовления'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='short_link',
            field=models.CharField(default='zB3E5g4GdUZTvWLMRJWbCm', max_length=128, unique=True),
        ),
    ]
