# Generated by Django 5.0.6 on 2024-06-17 10:44

import django.core.validators
import recipes.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0011_alter_favoriterecipe_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='favoriterecipe',
            name='recipe',
        ),
        migrations.RemoveField(
            model_name='favoriterecipe',
            name='user',
        ),
        migrations.RemoveField(
            model_name='shopingcart',
            name='recipe',
        ),
        migrations.RemoveField(
            model_name='shopingcart',
            name='user',
        ),
        migrations.AddField(
            model_name='tag',
            name='color',
            field=models.CharField(default='#FFFFFF', max_length=7, unique=True, validators=[recipes.validators.HexColorValidator], verbose_name='Цвет'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ingredientperrecipe',
            name='amount',
            field=models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MaxValueValidator(10000), django.core.validators.MinValueValidator(1)], verbose_name='Количество'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='cooking_time',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(600)], verbose_name='Время приготовления'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='short_link',
            field=models.CharField(default='85MqXYpz3aowxShkujrYUH', max_length=128, unique=True),
        ),
    ]
