# Generated by Django 5.0.6 on 2024-06-18 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0015_alter_recipe_short_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='short_link',
            field=models.CharField(default='jxxcPU2sQsc5fvCCJ6YLPq', max_length=128, unique=True),
        ),
    ]
