# Generated by Django 5.0.6 on 2024-06-18 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0020_alter_recipe_short_link_alter_shopingcart_recipe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='short_link',
            field=models.CharField(default='pzFNzb3bBwF8PiBbg2EUeh', max_length=128, unique=True),
        ),
    ]
