# NAMED VALUES THAT USED IN THE CODE OF FOODGRAM PROJECT ARE LOACTED HERE.
MAX_EMAIL_LENGTH = 254
MAX_USERNAME_LENGTH = 150
MAX_TEXT_DESCRIPTION = 512
MAX_TAG_LENGTH = 64
MAX_NAME = 128
MAX_UNIT_LENGTH = 16
