# Generated by Django 5.0.6 on 2024-06-07 06:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_subscriptions'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Subscriptions',
            new_name='Subscription',
        ),
        migrations.RenameField(
            model_name='subscription',
            old_name='subscription',
            new_name='subscriptable_user',
        ),
    ]
