# Generated by Django 5.0.6 on 2024-06-07 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_rename_subscriptions_subscription_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='avatar',
            field=models.ImageField(blank=True, upload_to='user_avatars/', verbose_name='Аватар пользователя'),
        ),
    ]
