# Generated by Django 5.0.6 on 2024-06-07 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_subscription_avatar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscription',
            name='avatar',
        ),
        migrations.AddField(
            model_name='customuser',
            name='avatar',
            field=models.ImageField(blank=True, upload_to='user_avatars/', verbose_name='Аватар пользователя'),
        ),
    ]
