# Generated by Django 5.0.6 on 2024-06-10 02:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_remove_subscription_avatar_customuser_avatar'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subscription',
            old_name='subscriptable_user',
            new_name='target_user',
        ),
    ]
